language: cpp
dist: xenial

matrix:
  include:
  - os: linux
    env: COMPILER=g++-7
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
  - os: linux
    env: COMPILER=clang++-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-7
        packages:
        - libstdc++-7-dev
        - clang-7
  - os: osx
    osx_image: xcode10.2

before_script:
- mkdir build
- cd build
- cmake -D CMAKE_CXX_COMPILER=$COMPILER ..

script: make
