#ifndef ISADE_F_FUNCTION_H
#define ISADE_F_FUNCTION_H

#include <memory>
#include "Function.h"

namespace adef {

class Configuration;
class PrototypeManager;

/**
@brief IsadeFFunction generates numbers according to
the procedure of the F value in the ISADE algorithm.

@c IsadeFFunction has the following feature:
- generate() : return the numbers generated by
the procedure of the F value in the ISADE algorithm.
- record() : record parameters into the object, min, average, current
            and/or tau component.
- update() : update values of the object, min, average, current and tau.

@par Requirement
record parameters into Function:
- name "object"
- name "min"
- name "average"
- name "current"
- name "tau"
.

ADEF supports many kinds of IsadeFFunction:
- IsadeFFunction.

@par The configuration
IsadeCrFunction has extra configurations:
- member
    - name: "object"
    - value: object configuration which is the ::RealVariableFunction.
- member
    - name: "min"
    - value: object configuration which is the ::RealVariableFunction.
- member
    - name: "average"
    - value: object configuration which is the ::RealVariableFunction.
- member
    - name: "current"
    - value: object configuration which is the ::RealVariableFunction.
- member
    - name: "tau"
    - value: object configuration which is the class derived from
             Function.
.
See setup() for the details.
*/
class IsadeFFunction : public Function<double>
{
public:

    using T = double;

/// @copydoc Function::Object
    using Object = typename Function<T>::Object;

/**
@brief Clone the current class.
@sa clone_impl()
*/
    std::shared_ptr<IsadeFFunction> clone() const
    {
        return std::dynamic_pointer_cast<IsadeFFunction>(clone_impl());
    }
/**
@brief Set up the internal states.

If @em SomeThing is the IsadeFFunction and
has the following configuration:
- object: ::RealVariableFunction of object 0.5
- tau: ::RealConstantFunction of object 0.1
.
its configuration should be
- JSON configuration
@code
"SomeThing" : {
    "classname" : "IsadeFFunction",
    "object" : {
        "classname" : "RealVariableFunction",
        "object" : 0.5
    },
    "min" : {
        "classname" : "RealVariableFunction"
    },
    "average" : {
        "classname" : "RealVariableFunction"
    },
    "current" : {
        "classname" : "RealVariableFunction"
    },
    "tau" : {
        "classname" : "RealConstantFunction",
        "object" : 0.1
    }
}
@endcode
*/
    void setup(const Configuration& config, const PrototypeManager& pm) override;

    Object generate() override;

    void update() override;

    unsigned int number_of_parameters() const override;

private:

/// The value of the parameter.
    Object object_;
/// The value of the min of fitness.
    Object min_;
/// The value of the average of fitness.
    Object average_;
/// The value of the fitness of the current individual.
    Object current_;
/// The value of the tau.
    Object tau_;

private:

    std::shared_ptr<Prototype> clone_impl() const override
    {
        return std::make_shared<IsadeFFunction>(*this);
    }
};

}

#endif // ISADE_F_FUNCTION_H
