#ifndef JDE_CR_FUNCTION_H
#define JDE_CR_FUNCTION_H

#include <memory>
#include <vector>
#include <string>
#include <random>
#include "Function.h"
#include "Any.h"
#include "Configuration.h"
#include "PrototypeManager.h"
#include "Individual.h"

namespace adef {

/**
@brief JdeCrFunction generates numbers according to
the procedure of the CR value in the JDE algorithm.

JdeCrFunction has the following feature:
- generate(): return the number generated by
the procedure of the CR value in the JDE algorithm.
- record(): record parameters into the object and/or tau component.
- update(): update values of the object and tau.

@par Requirement
record parameters into Function:
- name "object"
- name "tau"
.

ADEF supports many kinds of JdeCrFunction:
- JdeCrFunction.

@par The configuration
JdeCrFunction has extra configurations:
- member
    - name: "object"
    - value: object configuration which is the ::RealVariableFunction.
- member
    - name: "tau"
    - value: object configuration which is the class derived from
             Function.
.
See setup() for the details.
*/
class JdeCrFunction : public Function<double>
{
public:

    using T = double;

/// @copydoc Function::Object
    using Object = typename Function<T>::Object;

/**
@brief Clone the current class.
@sa clone_impl()
*/
    std::shared_ptr<JdeCrFunction> clone() const
    {
        return std::dynamic_pointer_cast<JdeCrFunction>(clone_impl());
    }
/**
@brief Set up the internal states.

If @em SomeThing is the JdeCrFunction and
has the following configuration:
- object: ::RealVariableFunction of object 0.9
- tau: ::RealConstantFunction of object 0.1
.
its configuration should be
- JSON configuration
@code
"SomeThing" : {
    "classname" : "JdeCrFunction",
    "object" : {
        "classname" : "RealVariableFunction",
        "object" : 0.9
    },
    "tau" : {
        "classname" : "RealConstantFunction",
        "object" : 0.1
    }
}
@endcode
.
*/
    void setup(const Configuration& config, const PrototypeManager& pm) override
    {
        auto object_config = config.get_config("object");
        auto object = make_and_setup_type<BaseFunction>(object_config, pm);
        object->set_function_name("object");
        add_function(object);

        auto tau_config = config.get_config("tau");
        auto tau = make_and_setup_type<BaseFunction>(tau_config, pm);
        tau->set_function_name("tau");
        add_function(tau);

        object_ = 0.9;
        tau_ = 0.1;
    }

    Object generate() override
    {
        std::mt19937 gen(std::rand());
        std::uniform_real_distribution<> uniform;
        if (uniform(gen) < tau_) {
            return uniform(gen);
        }
        else {
            return object_;
        }
    }

    void update() override
    {
        auto object = get_function("object");
        object->update();
        object_ = object->generate();

        auto tau = get_function("tau");
        tau->update();
        tau_ = tau->generate();
    }

    unsigned int number_of_parameters() const override
    {
        return 0;
    }

private:

/// The value of the parameter.
    Object object_;
/// The value of the tau.
    Object tau_;

private:

    std::shared_ptr<Prototype> clone_impl() const override
    {
        return std::make_shared<JdeCrFunction>(*this);
    }
};

}

#endif // JDE_CR_FUNCTION_H
