#ifndef JDE_F_FUNCTION_H
#define JDE_F_FUNCTION_H

#include <memory>
#include "Function.h"

namespace adef {

class Configuration;
class PrototypeManager;

/**
@brief JdeFFunction generates numbers according to
the procedure of the F value in the JDE algorithm.

JdeFFunction has the following feature:
- generate(): return the number generated by
the procedure of the F value in the JDE algorithm.
- record(): record parameters into the object, lower bound,
            upper bound and/or tau component.
- update(): update values of the object, lower bound, upper bound and tau.

@par Requirement
record parameters into Function:
- name "object"
- name "lower_bound"
- name "upper_bound"
- name "tau"
.

ADEF supports many kinds of JdeFFunction:
- JdeFFunction.

@par The configuration
JdeFFunction has extra configurations:
- member
    - name: "object"
    - value: object configuration which is the ::RealVariableFunction.
- member
    - name: "lower_bound"
    - value: object configuration which is the class derived from
             Function.
- member
    - name: "upper_bound"
    - value: object configuration which is the class derived from
             Function.
- member
    - name: "tau"
    - value: object configuration which is the class derived from
             Function.
.
See setup() for the details.
*/
class JdeFFunction : public Function<double>
{
public:

    using T = double;

/// @copydoc Function::Object
    using Object = typename Function<T>::Object;

/**
@brief Clone the current class.
@sa clone_impl()
*/
    std::shared_ptr<JdeFFunction> clone() const
    {
        return std::dynamic_pointer_cast<JdeFFunction>(clone_impl());
    }
/**
@brief Set up the internal states.

If @em SomeThing is the JdeFFunction and
has the following configuration:
- object: ::RealVariableFunction of object 0.5
- lower_bound: ::RealConstantFunction of object 0.1
- upper_bound: ::RealConstantFunction of object 0.9
- tau: ::RealConstantFunction of object 0.1
.
its configuration should be
- JSON configuration
@code
"SomeThing" : {
    "classname" : "JdeFFunction",
    "object" : {
        "classname" : "RealVariableFunction",
        "object" : 0.5
    },
    "lower_bound" : {
        "classname" : "RealConstantFunction",
        "object" : 0.1
    },
    "upper_bound" : {
        "classname" : "RealConstantFunction",
        "object" : 0.9
    },
    "tau" : {
        "classname" : "RealConstantFunction",
        "object" : 0.1
    }
}
@endcode
.
*/
    void setup(const Configuration& config, const PrototypeManager& pm) override;

    Object generate() override;

    void update() override;

    unsigned int number_of_parameters() const override;

private:

/// The value of the parameter.
    Object object_;
/// The value of the lower bound_.
    Object lower_bound_;
/// The value of the upper bound_.
    Object upper_bound_;
/// The value of the tau.
    Object tau_;

private:

    std::shared_ptr<Prototype> clone_impl() const override
    {
        return std::make_shared<JdeFFunction>(*this);
    }
};

}

#endif // JDE_F_FUNCTION_H
