#ifndef JDE_F_FUNCTION_H
#define JDE_F_FUNCTION_H

#include <memory>
#include <vector>
#include <string>
#include <random>
#include "Function.h"
#include "Any.h"
#include "Configuration.h"
#include "PrototypeManager.h"
#include "Individual.h"
#include "Random.h"

namespace adef {

/**
@brief JdeFFunction generates numbers according to
the procedure of the F value in the JDE algorithm.

JdeFFunction has the following feature:
- generate(): return the number generated by
the procedure of the F value in the JDE algorithm.
- record(): record parameters into the object, lower bound,
            upper bound and/or tau component.
- update(): update values of the object, lower bound, upper bound and tau.

@par Requirement
record parameters into Function:
- name "object"
- name "lower_bound"
- name "upper_bound"
- name "tau"
.

ADEF supports many kinds of JdeFFunction:
- JdeFFunction.

@par The configuration
JdeFFunction has extra configurations:
- member
    - name: "object"
    - value: object configuration which is the ::RealVariableFunction.
- member
    - name: "lower_bound"
    - value: object configuration which is the class derived from
             Function.
- member
    - name: "upper_bound"
    - value: object configuration which is the class derived from
             Function.
- member
    - name: "tau"
    - value: object configuration which is the class derived from
             Function.
.
See setup() for the details.
*/
class JdeFFunction : public Function<double>
{
public:

    using T = double;

/// @copydoc Function::Object
    using Object = typename Function<T>::Object;

/**
@brief Clone the current class.
@sa clone_impl()
*/
    std::shared_ptr<JdeFFunction> clone() const
    {
        return std::dynamic_pointer_cast<JdeFFunction>(clone_impl());
    }
/**
@brief Set up the internal states.

If @em SomeThing is the JdeFFunction and
has the following configuration:
- object: ::RealVariableFunction of object 0.5
- lower_bound: ::RealConstantFunction of object 0.1
- upper_bound: ::RealConstantFunction of object 0.9
- tau: ::RealConstantFunction of object 0.1
.
its configuration should be
- JSON configuration
@code
"SomeThing" : {
    "classname" : "JdeFFunction",
    "object" : {
        "classname" : "RealVariableFunction",
        "object" : 0.5
    },
    "lower_bound" : {
        "classname" : "RealConstantFunction",
        "object" : 0.1
    },
    "upper_bound" : {
        "classname" : "RealConstantFunction",
        "object" : 0.9
    },
    "tau" : {
        "classname" : "RealConstantFunction",
        "object" : 0.1
    }
}
@endcode
.
*/
    void setup(const Configuration& config, const PrototypeManager& pm) override
    {
        auto object_config = config.get_config("object");
        auto object = make_and_setup_type<BaseFunction>(object_config, pm);
        object->set_function_name("object");
        add_function(object);

        auto lower_bound_config = config.get_config("lower_bound");
        auto lower_bound = make_and_setup_type<BaseFunction>(lower_bound_config, pm);
        lower_bound->set_function_name("lower_bound");
        add_function(lower_bound);

        auto upper_bound_config = config.get_config("upper_bound");
        auto upper_bound = make_and_setup_type<BaseFunction>(upper_bound_config, pm);
        upper_bound->set_function_name("upper_bound");
        add_function(upper_bound);

        auto tau_config = config.get_config("tau");
        auto tau = make_and_setup_type<BaseFunction>(tau_config, pm);
        tau->set_function_name("tau");
        add_function(tau);

        object_ = 0.5;
        lower_bound_ = 0.1;
        upper_bound_ = 0.9;
        tau_ = 0.1;
    }

    Object generate() override
    {
        std::mt19937 gen(random_->random());
        std::uniform_real_distribution<> uniform;
        if (uniform(gen) < tau_) {
            return lower_bound_ +
                   uniform(gen) * upper_bound_;
        }
        else {
            return object_;
        }
    }

    void update() override
    {
        auto object = get_function("object");
        object->update();
        object_ = object->generate();

        auto lower_bound = get_function("lower_bound");
        lower_bound->update();
        lower_bound_ = lower_bound->generate();

        auto upper_bound = get_function("upper_bound");
        upper_bound->update();
        upper_bound_ = upper_bound->generate();

        auto tau = get_function("tau");
        tau->update();
        tau_ = tau->generate();
    }

    unsigned int number_of_parameters() const override
    {
        return 0;
    }

private:

/// The value of the parameter.
    Object object_;
/// The value of the lower bound_.
    Object lower_bound_;
/// The value of the upper bound_.
    Object upper_bound_;
/// The value of the tau.
    Object tau_;

private:

    std::shared_ptr<Prototype> clone_impl() const override
    {
        return std::make_shared<JdeFFunction>(*this);
    }
};

}

#endif // JDE_F_FUNCTION_H
